#!/usr/bin/env bash



\cp /etc/ssh/sshd_config /etc/ssh/sshd_config.ori
sed -i 's#PermitRootLogin yes#PermitRootLogin no#g'  /etc/ssh/sshd_config
sed -i 's#\#UseDNS yes#UseDNS no#g' /etc/ssh/sshd_config
sed -i 's#GSSAPIAuthentication yes#GSSAPIAuthentication no#g' /etc/ssh/sshd_config

systemctl restart sshd
netstat -ntulp|grep 8012


echo "Port 8012" >> /etc/ssh/sshd_config
systemctl restart sshd
netstat -ntulp|grep 8012

java1 java3  监听内网22端口

java2要以22连接到对端
java2

172.18.101.45 java1
172.18.101.44 java2
172.18.101.43 java3

echo 'ListenAddress 172.18.101.45:8012'>>  /etc/ssh/sshd_config
systemctl restart sshd
netstat -ntulp|grep 8012


echo 'ListenAddress 172.18.101.43:8012'>>  /etc/ssh/sshd_config
systemctl restart sshd
netstat -ntulp|grep 8012



yum install -y iptables-services
vim /etc/sysconfig/iptables


java2:
cat  /etc/sysconfig/iptables
# Firewall configuration written by system-config-firewall
# Manual customization of this file is not recommended.
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -m state --state NEW -m tcp -s 10.26.208.129 -p tcp --dport 10050 -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 8012 -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 22 -j ACCEPT
#-A INPUT -p tcp -m state --state NEW --dport 8000 -j ACCEPT
-A INPUT -p tcp -m state --state NEW --dport 111 -j ACCEPT
-A INPUT -p udp -m state --state NEW --dport 111 -j ACCEPT
-A INPUT -p tcp -m state --state NEW --dport 875 -j ACCEPT
-A INPUT -p udp -m state --state NEW --dport 875 -j ACCEPT
-A INPUT -p tcp -m state --state NEW --dport 2049 -j ACCEPT
-A INPUT -p udp -m state --state NEW --dport 2049 -j ACCEPT
-A INPUT -p udp -m state --state NEW --dport 6027 -j ACCEPT
-A INPUT -p udp -m state --state NEW --dport 5012 -j ACCEPT
-A INPUT -p udp -m state --state NEW --dport 54680 -j ACCEPT
-A INPUT -p udp -m state --state NEW --dport 30706 -j ACCEPT
-A INPUT -p udp -m state --state NEW --dport 24624 -j ACCEPT
-A INPUT -p udp -m state --state NEW --dport 10220 -j ACCEPT
-A INPUT -p tcp -m state --state NEW --dport 33077 -j ACCEPT
-A INPUT -p tcp -m state --state NEW --dport 27884 -j ACCEPT
-A INPUT -p tcp -m state --state NEW --dport 41692 -j ACCEPT
-A INPUT -p tcp -m state --state NEW --dport 7286 -j ACCEPT
-A INPUT -s 10.26.71.155 -p tcp -m tcp --dport 8000 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 5666 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 8080 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 873 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 3306 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 11211 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 11212 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 3333 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 9090 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
COMMIT


java1:
# Firewall configuration written by system-config-firewall
# Manual customization of this file is not recommended.
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -m state --state NEW -s 10.26.208.129 -m tcp -p tcp --dport 10050 -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 8012 -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 22 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 5666 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 8080 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 8000 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 8001 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 11211 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 20880 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 9301 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 9302 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
COMMIT



java3:
# Generated by iptables-save v1.4.7 on Tue Oct 25 12:21:23 2016
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [39523:5690151]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp -s 10.26.208.129 --dport 10050 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 111 -j ACCEPT
-A INPUT -p udp -m state --state NEW -m udp --dport 111 -j ACCEPT
-A INPUT -p tcp -m state --state NEW --dport 2049 -j ACCEPT
-A INPUT -p udp -m state --state NEW --dport 2049 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 8013 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 7070 -j ACCEPT
-A INPUT -p udp -m udp --dport 1194 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 8080 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 8090 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 11211 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 1723 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
COMMIT
# Completed on Tue Oct 25 12:21:23 2016
# Generated by iptables-save v1.4.7 on Tue Oct 25 12:21:23 2016
*nat
:PREROUTING ACCEPT [2633:158714]
:POSTROUTING ACCEPT [1598:96206]
:OUTPUT ACCEPT [1598:96206]
-A POSTROUTING -s 172.16.0.0/16 -o eth1 -j SNAT --to-source 120.25.59.74
COMMIT
# Completed on Tue Oct 25 12:21:23 2016


java4:
# Generated by iptables-save v1.4.7 on Wed Oct 21 10:50:06 2015
*nat
:PREROUTING ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A POSTROUTING -s 10.8.0.0/24 -j SNAT --to-source 10.170.149.224
COMMIT
# Completed on Wed Oct 21 10:50:06 2015
# Generated by iptables-save v1.4.7 on Wed Oct 21 10:50:06 2015
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [3613313:677971214]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp -s 10.26.208.129 --dport 10050 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 111 -j ACCEPT
-A INPUT -p udp -m state --state NEW -m udp --dport 111 -j ACCEPT
-A INPUT -p tcp -m state --state NEW --dport 2049 -j ACCEPT
-A INPUT -p udp -m state --state NEW --dport 2049 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
-A INPUT -p udp -m udp --dport 1194 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 8080 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 9091 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 1985 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 6080 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 9092 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 9095 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 8012 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -s 10.116.139.116/32 -p tcp -m state --state NEW -m tcp --dport 3306 -j ACCEPT
-A INPUT -s 10.116.67.225/32 -p tcp -m state --state NEW -m tcp --dport 3306 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
COMMIT
# Completed on Wed Oct 21 10:50:06 201






*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [3613313:677971214]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
# zabbix
#-A INPUT -p tcp -m state --state NEW -m tcp -s 10.26.208.129 --dport 10050 -j ACCEPT

# ssh
-A INPUT -p tcp -m state --state NEW -m tcp --dport 8012 -j ACCEPT

# nginx
-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT

# tomcat
-A INPUT -p tcp -m tcp --dport 8080 -j ACCEPT

# nfs
-A INPUT -p tcp -m state --state NEW -m tcp --dport 111 -j ACCEPT
-A INPUT -p udp -m state --state NEW -m udp --dport 111 -j ACCEPT
-A INPUT -p tcp -m state --state NEW --dport 2049 -j ACCEPT
-A INPUT -p udp -m state --state NEW --dport 2049 -j ACCEPT

# memecached
-A INPUT -p tcp -m tcp --dport 11211 -j ACCEPT

# others
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
COMMIT


