apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: filebeat-test
  namespace: default
spec:
  replicas: 3
  template:
    metadata:
      labels:
        k8s-app: filebeat-test
    spec:
      containers:

      - image: filebeat-me:5.4.1
        name: filebeat
        volumeMounts:
        - name: app-logs
          mountPath: /log
        - name: filebeat-config
          mountPath: /etc/filebeat/

      - image: nginx:1.11.4-alpine
        name : app
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app-logs
          mountPath: /var/log/nginx

      volumes:
      - name: filebeat-config
        configMap:
          name: filebeat-config

      - name: app-logs
        emptyDir: {}


---
apiVersion: v1
kind: Service
metadata:
  name: filebeat-test
  labels:
    app: filebeat-test
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    run: filebeat-test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |
    filebeat.prospectors:
    - input_type: log
      paths:
        - "/log/*"
        - "/log/usermange/common/*"
    output.elasticsearch:
      hosts: ["elasticsearch.logging.svc.cluster.local:9200"]
    username: "elastic"
    password: "changeme"
    index: "filebeat-docker-test"

data:
  filebeat.yml: |
    filebeat.prospectors:
    - input_type: log
      fields:
        service-name: api
        #pod-ip:
      paths:
        - "/log/*"
      multiline:
        pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}:[0-9]{3}'
        negate: true
        match: after
    output.elasticsearch:
      hosts: ["elasticsearch.logging.svc.cluster.local:9200"]
      template.name: "filebeat"
      template.path: "filebeat.template.json"
      template.overwrite: true

    # Available log levels are: critical, error, warning, info, debug
    logging.level: info
